### ISSUE TITLE
please setup webhooks / travis

### ISSUE THREAD

**Issue by aviau** [absfs/afero#3]
Hello!

Would you please setup travis for the repository?

If you give me admin access, I can do it.

**Comment by JoshuaKolden** [comment]
Yes, good idea thanks.

**Comment by JoshuaKolden** [comment]
You now have admin

**Comment by aviau** [comment]
I just enabled travis and added the badge to the README.

I will have some time in the next 2 weeks so I intend to help a bit with absfs :)
