### ISSUE TITLE
Replace directory bool in memfs to proper os.FileMode flags. 

### ISSUE THREAD

**Issue by JoshuaKolden** [absfs/afero#5]

**Comment by aviau** [comment]
Did you run the tests? The tests break after this commit.

**Comment by JoshuaKolden** [comment]
Yes, but apparently only in the `memefs` dir.  My mistake.  I wouldn't have pushed to master if I thought these changes could effect tests in a different package.

Very odd that this internal change would have side effects. I'll try to fix it right now, or roll it back.

**Comment by aviau** [comment]
They cause a deadlock, which was fixed originally (I think) by this commit: https://github.com/spf13/afero/commit/787d034dfe70e44075ccc060d346146ef53270ad

**Comment by JoshuaKolden** [comment]
Wow what a miss. Those tests are illegible.  Passing for now though.
